### ISSUE TITLE
anaconda: more packages by default

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc-compute-docker#10]
Increase out of the box experience by adding more packages to https://github.com/sagemathinc/cocalc-compute-docker/blob/a95859b924fea7e93a5055110736c074ecfaed6d/src/anaconda/Dockerfile#L39

User report:

> I tried running jupyterlab on my computer server but it didn't recognize my custom kernels because the base image doesn't include `nb_conda_kernels`. Also when using Dask in jupyterlab, it's very nice to have the package `dask-labextension` which allows the dask dashboard components to be embedded in the JupyterLab layout.

**Comment by williamstein** [comment]
I want to keep the current Anaconda image minimal.   However, there can instead be two distinct images similar to what's done with Sage right now:

<img width="578" alt="image" src="https://github.com/sagemathinc/cocalc-compute-docker/assets/1276278/7b600226-c7d6-4bb7-9329-fba542a1dad5">

**Comment by williamstein** [comment]
It's extremely important having minimal images as an option, e.g., for supporting on prem and other pseudo clouds.

**Comment by williamstein** [comment]
I disagree with this for compute servers since anaconda installs are fast and should work.  This also basically greatly increase *my* maintenance load, meaning I have to constantly update images, rather than relying on anaconda/upstream to do that.
